use iepam;
INSERT INTO curso (`id_curso`,`id_usuario`,`nombre`,`descripcion`,`num_lecciones`,`imagen`) VALUES (1,1,'introduccion','En este curso se abarcará la introducción al uso de la plataforma para un usuario, se verán las diversas opciones con las que el usuario tiene en la plataforma',5,'https://factorcapitalhumano.com/wp-content/uploads/2021/03/plataforma-cursos-capacitacion-gratuitos.jpg');
INSERT INTO curso (`id_curso`,`id_usuario`,`nombre`,`descripcion`,`num_lecciones`,`imagen`) VALUES (2,1,'nodejs','La aparición de Node.js ha supuesto toda una revolución en el mundo de JavaScript.\n\nNode.js es uno de los lenguajes de programación más populares del mundo. Hoy en día, impulsa millones de sitios web, sin embargo esto no es lo único.\n\nSi hay algo que está creciendo a pasos agigantados es el desarrollo de APIs\n\nTe invito formar parte de este nuevo curso  API REST Nodejs desde cero usando MongoDB o MySQL en Udemy donde  aprenderás a construir una API Rest en Node desde cero aplicando paradigmas de la programación, utilizando rutas, modelos, controladores, cargas de archivo  solo debes tener el tiempo y disposición recuerda que puedes revisar el temario de todo lo que se explicara.',5,'https://s3-us-west-2.amazonaws.com/devcodepro/media/tutorials/instalacion-de-nodejs-en-ubuntu-t1.jpg');
INSERT INTO curso (`id_curso`,`id_usuario`,`nombre`,`descripcion`,`num_lecciones`,`imagen`) VALUES (3,1,'outlook','aprenda a usar Outlook en Windows, MacOS, iOS o Android, y Outlook en la Web a través de una serie de cursos de aprendizaje de Outlook.',5,'https://gloryittechnologies.com/img/help-center/96/microsoft-outlook-2019-review.jpg');
INSERT INTO curso (`id_curso`,`id_usuario`,`nombre`,`descripcion`,`num_lecciones`,`imagen`) VALUES (4,1,'FrontEnd Web Developer','Un curso paso a paso si deseas comenzar en el mundo de la programación Web.\n\nEn este curso aprenderás 10 Lenguajes y Tecnologías Web:\n\nHTML, CSS, SASS, Workflows, JavaScript, Fetch, PHP, MVC, MySQL y APIs',5,'https://3cthinkers.com/en/wp-content/uploads/2017/03/dynamicpages.jpeg');
INSERT INTO curso (`id_curso`,`id_usuario`,`nombre`,`descripcion`,`num_lecciones`,`imagen`) VALUES (5,1,'MySql','En este curso de MySQL aprenderás todo lo relacionado a la gestión, creación, clasificación y registro de datos e información, haciendo uso de este software. Es fácil de aprender y solo se requiere tener conocimientos elementales.',6,'https://edteam-media.s3.amazonaws.com/courses/original/3aa59acc-3472-4875-b9c6-216825be755b.png');
INSERT INTO curso (`id_curso`,`id_usuario`,`nombre`,`descripcion`,`num_lecciones`,`imagen`) VALUES (8,2,'Internet de las cosas II','El internet de las cosas1​ IdC, por sus siglas​ es un concepto que se refiere a una interconexión digital de objetos cotidianos con internet. Es, en definitiva, la conexión de internet más con objetos que con personas.​ También se suele conocer como internet de todas las cosas o internet sobre las cosas. Si los objetos de la vida cotidiana tuvieran incorporadas etiquetas de radio, podrían ser identificados y gestionados por otros equipos de la misma manera que si lo fuesen por seres humanos.5​6​',1,'https://www.latercera.com/resizer/uEWs8cBqz2f1hl3Ii6VGfo5ieeo=/900x600/smart/cloudfront-us-east-1.images.arcpublishing.com/copesa/YVBYP2C625FPDNVK6N5F5WFIBE.png');
INSERT INTO curso (`id_curso`,`id_usuario`,`nombre`,`descripcion`,`num_lecciones`,`imagen`) VALUES (11,7,'Hablar en público','Este curso está diseñado para todo aquel que desee o tenga la necesidad de hablar en publico. Ya sea delante de compañeros de trabajo, en clases universitarias o escolares, e iglesias o cualquier conglomerado. Hasta para convencer en una reunión de amigos. Para \"Speakers\" profesionales no es el objetivo, a menos que esté iniciando y lo tome como base.',1,'https://img-c.udemycdn.com/course/480x270/1883116_4983_3.jpg');
INSERT INTO curso (`id_curso`,`id_usuario`,`nombre`,`descripcion`,`num_lecciones`,`imagen`) VALUES (12,8,'Como hablar en público','Como comunicar ideas y ayudar a otros a aprender',1,'https://profesionistas.org.mx/wp-content/uploads/2018/10/Mesa-de-trabajo-1CIBERSEGURIDAD-CURSOS-.png');
